"files": [
  {
    "source": "/src/main/resources/assets/dawnoftimebuilder/lang/en_us.json",
    "translation": "/src/main/resources/assets/dawnoftimebuilder/lang/%locale_with_underscore%.json",
    "translation_replace": {
      "fr_FR": "fr_fr"
    }
  }
]