package org.dawnoftime.dawnoftime.client.gui.creative;

import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import org.dawnoftime.dawnoftime.registry.DoTBBlocksRegistry;
import org.dawnoftime.dawnoftime.registry.DoTBItemsRegistry;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.dawnoftime.dawnoftime.DoTBCommon.MOD_ID;



public enum CreativeInventoryCategories {
    GENERAL("general", null, List.of(
            new SubTab("building",
                    DoTBBlocksRegistry.INSTANCE.RAMMED_DIRT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RAMMED_DIRT_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RAMMED_DIRT_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RAMMED_DIRT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RAMMED_DIRT_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_WHEAT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_WHEAT_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_WHEAT_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_WHEAT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_WHEAT_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_BAMBOO.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_BAMBOO_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_BAMBOO_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_BAMBOO_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.THATCH_BAMBOO_EDGE.get().asItem(),
                    Blocks.GRAVEL.asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAVEL_SLAB.get().asItem(),
                    Blocks.COBBLESTONE.asItem(),
                    Blocks.COBBLESTONE_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.COBBLESTONE_PLATE.get().asItem(),
                    Blocks.COBBLESTONE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.COBBLESTONE_EDGE.get().asItem(),
                    Blocks.COBBLESTONE_WALL.asItem(),
                    Blocks.STONE.asItem(),
                    Blocks.STONE_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.STONE_PLATE.get().asItem(),
                    Blocks.STONE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.STONE_EDGE.get().asItem(),
                    Blocks.STONE_BRICKS.asItem(),
                    Blocks.STONE_BRICK_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_PLATE.get().asItem(),
                    Blocks.STONE_BRICK_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_EDGE.get().asItem(),
                    Blocks.STONE_BRICK_WALL.asItem(),
                    Blocks.SAND.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SAND_SLAB.get().asItem(),
                    Blocks.SANDSTONE.asItem(),
                    Blocks.SANDSTONE_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SANDSTONE_PLATE.get().asItem(),
                    Blocks.SANDSTONE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SANDSTONE_EDGE.get().asItem(),
                    Blocks.SANDSTONE_WALL.asItem(),
                    Blocks.SMOOTH_SANDSTONE.asItem(),
                    Blocks.SMOOTH_SANDSTONE_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SMOOTH_SANDSTONE_PLATE.get().asItem(),
                    Blocks.SMOOTH_SANDSTONE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SMOOTH_SANDSTONE_EDGE.get().asItem(),
                    Blocks.CUT_SANDSTONE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CUT_SANDSTONE_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CUT_SANDSTONE_PLATE.get().asItem(),
                    Blocks.CUT_SANDSTONE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CUT_SANDSTONE_EDGE.get().asItem(),
                    Blocks.CHISELED_SANDSTONE.asItem()
            ),
            new SubTab("wood",
                    Blocks.OAK_PLANKS.asItem(),
                    Blocks.OAK_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_PLANKS_PLATE.get().asItem(),
                    Blocks.OAK_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_OAK_LOG.asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_PERGOLA.get().asItem(),
                    Blocks.OAK_FENCE.asItem(),
                    Blocks.OAK_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_LATTICE.get().asItem(),
                    Blocks.OAK_DOOR.asItem(),
                    Blocks.OAK_TRAPDOOR.asItem(),
                    Blocks.OAK_LEAVES.asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_LEAVES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.OAK_LEAVES_EDGE.get().asItem(),
                    Blocks.ACACIA_PLANKS.asItem(),
                    Blocks.ACACIA_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_PLANKS_PLATE.get().asItem(),
                    Blocks.ACACIA_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_ACACIA_LOG.asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_PERGOLA.get().asItem(),
                    Blocks.ACACIA_FENCE.asItem(),
                    Blocks.ACACIA_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_LATTICE.get().asItem(),
                    Blocks.ACACIA_DOOR.asItem(),
                    Blocks.ACACIA_TRAPDOOR.asItem(),
                    Blocks.ACACIA_LEAVES.asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_LEAVES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.ACACIA_LEAVES_EDGE.get().asItem(),
                    Blocks.BAMBOO_PLANKS.asItem(),
                    Blocks.BAMBOO_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_PLANKS_PLATE.get().asItem(),
                    Blocks.BAMBOO_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_SUPPORT_BEAM.get().asItem(),
                    Blocks.BAMBOO_BLOCK.asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_PERGOLA.get().asItem(),
                    Blocks.BAMBOO_FENCE.asItem(),
                    Blocks.BAMBOO_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.BAMBOO_LATTICE.get().asItem(),
                    Blocks.BAMBOO_DOOR.asItem(),
                    Blocks.BAMBOO_TRAPDOOR.asItem(),
                    Blocks.DARK_OAK_PLANKS.asItem(),
                    Blocks.DARK_OAK_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_PLANKS_PLATE.get().asItem(),
                    Blocks.DARK_OAK_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_DARK_OAK_LOG.asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_PERGOLA.get().asItem(),
                    Blocks.DARK_OAK_FENCE.asItem(),
                    Blocks.DARK_OAK_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_LATTICE.get().asItem(),
                    Blocks.DARK_OAK_DOOR.asItem(),
                    Blocks.DARK_OAK_TRAPDOOR.asItem(),
                    Blocks.DARK_OAK_LEAVES.asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_LEAVES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.DARK_OAK_LEAVES_EDGE.get().asItem(),
                    Blocks.CHERRY_PLANKS.asItem(),
                    Blocks.CHERRY_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_PLANKS_PLATE.get().asItem(),
                    Blocks.CHERRY_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_CHERRY_LOG.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_PERGOLA.get().asItem(),
                    Blocks.CHERRY_FENCE.asItem(),
                    Blocks.CHERRY_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_LATTICE.get().asItem(),
                    Blocks.CHERRY_DOOR.asItem(),
                    Blocks.CHERRY_TRAPDOOR.asItem(),
                    Blocks.CHERRY_LEAVES.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_LEAVES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHERRY_LEAVES_EDGE.get().asItem(),
                    Blocks.MANGROVE_PLANKS.asItem(),
                    Blocks.MANGROVE_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_PLANKS_PLATE.get().asItem(),
                    Blocks.MANGROVE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_MANGROVE_LOG.asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_PERGOLA.get().asItem(),
                    Blocks.MANGROVE_FENCE.asItem(),
                    Blocks.MANGROVE_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_LATTICE.get().asItem(),
                    Blocks.MANGROVE_DOOR.asItem(),
                    Blocks.MANGROVE_TRAPDOOR.asItem(),
                    Blocks.MANGROVE_LEAVES.asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_LEAVES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.MANGROVE_LEAVES_EDGE.get().asItem(),
                    Blocks.CRIMSON_PLANKS.asItem(),
                    Blocks.CRIMSON_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_PLANKS_PLATE.get().asItem(),
                    Blocks.CRIMSON_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_CRIMSON_STEM.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_PERGOLA.get().asItem(),
                    Blocks.CRIMSON_FENCE.asItem(),
                    Blocks.CRIMSON_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.CRIMSON_LATTICE.get().asItem(),
                    Blocks.CRIMSON_DOOR.asItem(),
                    Blocks.CRIMSON_TRAPDOOR.asItem(),
                    Blocks.NETHER_WART_BLOCK.asItem(),
                    Blocks.WARPED_PLANKS.asItem(),
                    Blocks.WARPED_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_PLANKS_PLATE.get().asItem(),
                    Blocks.WARPED_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_SUPPORT_BEAM.get().asItem(),
                    Blocks.STRIPPED_WARPED_STEM.asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_PERGOLA.get().asItem(),
                    Blocks.WARPED_FENCE.asItem(),
                    Blocks.WARPED_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.WARPED_LATTICE.get().asItem(),
                    Blocks.WARPED_DOOR.asItem(),
                    Blocks.WARPED_TRAPDOOR.asItem(),
                    Blocks.WARPED_WART_BLOCK.asItem()
            ),
            new SubTab("colored",
                    Blocks.WHITE_CONCRETE.asItem(),
                    Blocks.ORANGE_CONCRETE.asItem(),
                    Blocks.MAGENTA_CONCRETE.asItem(),
                    Blocks.LIGHT_BLUE_CONCRETE.asItem(),
                    Blocks.YELLOW_CONCRETE.asItem(),
                    Blocks.LIME_CONCRETE.asItem(),
                    Blocks.PINK_CONCRETE.asItem(),
                    Blocks.GRAY_CONCRETE.asItem(),
                    Blocks.LIGHT_GRAY_CONCRETE.asItem(),
                    Blocks.CYAN_CONCRETE.asItem(),
                    Blocks.PURPLE_CONCRETE.asItem(),
                    Blocks.BLUE_CONCRETE.asItem(),
                    Blocks.BROWN_CONCRETE.asItem(),
                    Blocks.GREEN_CONCRETE.asItem(),
                    Blocks.RED_CONCRETE.asItem(),
                    Blocks.BLACK_CONCRETE.asItem()
            )
    )),
    JAPANESE("japanese", "https://www.youtube.com/watch?v=AxJGk-deTmo&list=PLRp3sDcdVhnSw-C9jHe_ykJZc5AurcvyG", List.of(
            new SubTab("building",
                    DoTBBlocksRegistry.INSTANCE.STRAIGHT_RAKED_GRAVEL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CURVED_RAKED_GRAVEL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.STEPPING_STONES.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.STEPPING_STONES_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_FOUNDATION.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_BOARDS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_BOARDS_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_BOARDS_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_BOARDS_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_BOARDS_EDGE.get().asItem(),
                    Blocks.SPRUCE_PLANKS.asItem(),
                    Blocks.SPRUCE_STAIRS.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_PLANKS_PLATE.get().asItem(),
                    Blocks.SPRUCE_SLAB.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_SUPPORT_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_ROOF_SUPPORT.get().asItem(),
                    Blocks.STRIPPED_SPRUCE_LOG.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_PERGOLA.get().asItem(),
                    Blocks.SPRUCE_FENCE.asItem(),
                    Blocks.SPRUCE_FENCE_GATE.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_LATTICE.get().asItem(),
                    Blocks.SPRUCE_DOOR.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_PAPER_DOOR.get().asItem(),
                    Blocks.SPRUCE_TRAPDOOR.asItem(),
                    Blocks.SPRUCE_LEAVES.asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_LEAVES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_LEAVES_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_PLANKS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_PLANKS_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_PLANKS_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_PLANKS_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_PLANKS_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_SUPPORT_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_BOARDS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_FOUNDATION.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_FOUNDATION_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_LOG_STRIPPED.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_PERGOLA.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_FENCE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_FENCE_GATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_RAILING.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_FANCY_RAILING.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_LATTICE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_DOOR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_TRAPDOOR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_SHUTTERS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_TALL_SHUTTERS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_ROOF_SUPPORT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_GLASS_PANE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_WINDOW.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_WATTLE_AND_DAUB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_WATTLE_AND_DAUB_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_WATTLE_AND_DAUB_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_WATTLE_AND_DAUB_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_WATTLE_AND_DAUB_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_TIMBER_FRAME.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CHARRED_SPRUCE_TIMBER_FRAME_PILLAR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_TIMBER_FRAME.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_TIMBER_FRAME_PILLAR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_LOG.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_PERGOLA.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_FENCE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_RAILING.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_FANCY_RAILING.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_SUPPORT_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_SUPPORT_BEAM.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_ROOF_SUPPORT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.REINFORCED_RED_PAINTED_RELIEF.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_DOOR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_WINDOWED_DOOR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_SHUTTERS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAINTED_SMALL_SHUTTER.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.RED_PAPER_LANTERN.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_WALL_FLAT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_WALL_SQUARED.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_WALL_WINDOWS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_WALL_FLOWERY.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_DOOR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAY_ROOF_TILES.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAY_ROOF_TILES_STAIRS.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAY_ROOF_TILES_PLATE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAY_ROOF_TILES_SLAB.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAY_ROOF_TILES_EDGE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.GRAY_ROOF_TILES_WALL.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.STONE_LANTERN.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.PAPER_LAMP.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.IRORI_FIREPLACE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.FIREPLACE.get().asItem(),
                    Items.FLINT_AND_STEEL,
                    DoTBItemsRegistry.INSTANCE.UNFIRED_CLAY_ROOF_TILE.get(),
                    DoTBItemsRegistry.INSTANCE.GRAY_CLAY_ROOF_TILE.get(),
                    DoTBItemsRegistry.INSTANCE.JAPANESE_EMBLEM.get()
            ),
            new SubTab("furniture",
                    DoTBBlocksRegistry.INSTANCE.PAPER_FOLDING_SCREEN.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_LITTLE_FLAG.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SMALL_TATAMI_MAT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.TATAMI_MAT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.LIGHT_GRAY_FUTON.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.WHITE_CUSHION.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_LEGLESS_CHAIR.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SPRUCE_LOW_TABLE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.IKEBANA_FLOWER_POT.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SAKE_BOTTLE.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.SAKE_CUP.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CAST_IRON_TEAPOT_GRAY.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CAST_IRON_TEACUP_GRAY.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CAST_IRON_TEAPOT_GREEN.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CAST_IRON_TEACUP_GREEN.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CAST_IRON_TEAPOT_DECORATED.get().asItem(),
                    DoTBBlocksRegistry.INSTANCE.CAST_IRON_TEACUP_DECORATED.get().asItem()
            )
    )),

    GERMAN("german", "https://www.youtube.com/watch?v=g_GulBiXvXs&list=PLRp3sDcdVhnSzsKrXbCEMr-833Em-ntDF",

            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_FRAMED_RAMMED_DIRT.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_FRAMED_RAMMED_DIRT_PILLAR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WATTLE_AND_DAUB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WATTLE_AND_DAUB_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WATTLE_AND_DAUB_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WATTLE_AND_DAUB_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WATTLE_AND_DAUB_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TIMBER_FRAME.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TIMBER_FRAME_PILLAR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TIMBER_FRAME_CORNER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TIMBER_FRAME_CROSSED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TIMBER_FRAME_SQUARED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.REINFORCED_WAXED_OAK.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.SCULPTED_WAXED_OAK.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SCULPTED_WAXED_OAK_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SCULPTED_WAXED_OAK_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SCULPTED_WAXED_OAK_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SCULPTED_WAXED_OAK_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_PLANKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_PLANKS_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_PLANKS_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_PLANKS_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_PLANKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_SUPPORT_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_SUPPORT_BEAM.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_LOG_STRIPPED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_BEAM.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_PERGOLA.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_FENCE_GATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_BALUSTER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_LATTICE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_DOOR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TRAPDOOR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_SMALL_SHUTTER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_SHUTTER.get().asItem(),
            Blocks.OAK_LEAVES.asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_LEAVES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_LEAVES_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LATTICE_GLASS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LATTICE_GLASS_PANE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LATTICE_WAXED_OAK_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LATTICE_STONE_BRICKS_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MASONRY.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MASONRY_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MASONRY_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MASONRY_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MASONRY_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MASONRY_WALL.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_ARROWSLIT.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_MACHICOLATION.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_FIREPLACE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_CHIMNEY.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_POOL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_SMALL_POOL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_FAUCET.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.STONE_BRICKS_WATER_JET.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WATER_SOURCE_TRICKLE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FLAT_ROOF_TILES_CHIMNEY.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.IRON_PORTCULLIS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WROUGHT_IRON_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.CANDLESTICK.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_CHANDELIER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_TABLE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_OAK_CHAIR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FIREPLACE.get().asItem(),
            Items.FLINT_AND_STEEL,
            DoTBItemsRegistry.INSTANCE.GERMAN_EMBLEM.get()
    ),
    
    ROMAN("roman", "https://www.youtube.com/watch?v=7TgxqQHGVlo&list=PLRp3sDcdVhnQNEcVV6Zi0NvG0p80IhaZo",

            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_WALL.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.SANDSTONE_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_SIDED_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.COVERED_SANDSTONE_WALL.get().asItem(),
            Blocks.BIRCH_PLANKS.asItem(),
            Blocks.BIRCH_STAIRS.asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_PLANKS_PLATE.get().asItem(),
            Blocks.BIRCH_SLAB.asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_PLANKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_SUPPORT_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_SUPPORT_BEAM.get().asItem(),
            Blocks.STRIPPED_BIRCH_LOG.asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_BEAM.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_PERGOLA.get().asItem(),
            Blocks.BIRCH_FENCE.asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_LATTICE.get().asItem(),
            Blocks.BIRCH_DOOR.asItem(),
            Blocks.BIRCH_TRAPDOOR.asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_FANCY_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_FOOTSTOOL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_COUCH.get().asItem(),
            Blocks.BIRCH_LEAVES.asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_LEAVES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIRCH_LEAVES_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.ROMAN_FRESCO_BLACK.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROMAN_FRESCO_RED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MOSAIC_FLOOR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MOSAIC_FLOOR_DELICATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MOSAIC_FLOOR_ROSETTE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_PILLAR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_COFFER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_COFFER_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_SIDED_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_FANCY_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_STATUE_MARS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MARBLE_BIG_FLOWER_POT.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_WHITE_TERRACOTTA.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_WHITE_TERRACOTTA_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_WHITE_TERRACOTTA_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_WHITE_TERRACOTTA_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_WHITE_TERRACOTTA_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_WHITE_TERRACOTTA_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_BLACK_TERRACOTTA.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_BLACK_TERRACOTTA_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_BLACK_TERRACOTTA_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_BLACK_TERRACOTTA_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_BLACK_TERRACOTTA_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SMOOTH_BLACK_TERRACOTTA_WALL.get().asItem(),
            Blocks.TERRACOTTA.asItem(),
            DoTBBlocksRegistry.INSTANCE.TERRACOTTA_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.TERRACOTTA_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.TERRACOTTA_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.TERRACOTTA_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.TERRACOTTA_WALL.get().asItem(),
            Blocks.RED_TERRACOTTA.asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_TERRACOTTA_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_TERRACOTTA_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_TERRACOTTA_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_TERRACOTTA_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_TERRACOTTA_WALL.get().asItem(),
            Blocks.ORANGE_TERRACOTTA.asItem(),
            DoTBBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OCHRE_ROOF_TILES.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OCHRE_ROOF_TILES_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OCHRE_ROOF_TILES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OCHRE_ROOF_TILES_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OCHRE_ROOF_TILES_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OCHRE_ROOF_TILES_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BIG_FLOWER_POT.get().asItem(),
            Blocks.CHAIN.asItem(),
            DoTBBlocksRegistry.INSTANCE.IRON_FANCY_LANTERN.get().asItem(),
            Blocks.LANTERN.asItem(),
            DoTBItemsRegistry.INSTANCE.UNFIRED_CLAY_TILE.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE_ORANGE.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE_BLACK.get(),
            DoTBItemsRegistry.INSTANCE.ROMAN_EMBLEM.get()
    ),
    PRE_COLOMBIAN("pre_columbian", "https://www.youtube.com/watch?v=jR-dWUqHgQ8&list=PLRp3sDcdVhnTP3E2QNE-2E-inx1K51Btu",
            DoTBBlocksRegistry.INSTANCE.PUUC_COBBLED_LIMESTONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_COBBLED_LIMESTONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_COBBLED_LIMESTONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_COBBLED_LIMESTONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_COBBLED_LIMESTONE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_WAVE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_CROSSED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_TIGHT_LATTICE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PUUC_LIMESTONE_DECORATED.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_PUUC_LIMESTONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_PUUC_LIMESTONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_PUUC_LIMESTONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_PUUC_LIMESTONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_PUUC_LIMESTONE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_PUUC_LIMESTONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_PUUC_LIMESTONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_PUUC_LIMESTONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_PUUC_LIMESTONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_PUUC_LIMESTONE_EDGE.get().asItem(),

            Blocks.JUNGLE_PLANKS.asItem(),
            Blocks.JUNGLE_STAIRS.asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_PLANKS_PLATE.get().asItem(),
            Blocks.JUNGLE_SLAB.asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_PLANKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_SUPPORT_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_SUPPORT_BEAM.get().asItem(),
            Blocks.STRIPPED_JUNGLE_LOG.asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_BEAM.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_PERGOLA.get().asItem(),
            Blocks.JUNGLE_FENCE.asItem(),
            Blocks.JUNGLE_FENCE_GATE.asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_LATTICE.get().asItem(),
            Blocks.JUNGLE_DOOR.asItem(),
            Blocks.JUNGLE_TRAPDOOR.asItem(),
            Blocks.JUNGLE_LEAVES.asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_LEAVES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.JUNGLE_LEAVES_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WHITE_SPIRAL_TEMPLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WHITE_PAINTED_LATTICE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_BLUE_WAVE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_BLUE_ROUND.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_WHITE_SPIRAL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_CRENELATION.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_STONE_FRIEZE_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PAINTED_LATTICE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.BLUE_PAINTED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_PLASTERED_STONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_PLASTERED_STONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_PLASTERED_STONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_PLASTERED_STONE_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_WAVE_TEMPLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLUE_ROUND_TEMPLATE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.GREEN_PAINTED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PLASTERED_STONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PLASTERED_STONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PLASTERED_STONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PLASTERED_STONE_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.YELLOW_PAINTED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.YELLOW_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.YELLOW_PLASTERED_STONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.YELLOW_PLASTERED_STONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.YELLOW_PLASTERED_STONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.YELLOW_PLASTERED_STONE_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.RED_ORNAMENTED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.CHISELED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.CHISELED_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ORNAMENTED_CHISELED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_CHISELED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_ORNAMENTED_CHISELED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_ORNAMENTED_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_SCULPTED_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_SMALL_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_CHISELED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_ORNAMENTED_CHISELED_PLASTERED_STONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_ORNAMENTED_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_SCULPTED_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_SMALL_PLASTERED_STONE_FRIEZE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PLASTERED_STONE_CRESSET.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FEATHERED_SERPENT_SCULPTURE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SERPENT_SCULPTED_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FIREPLACE.get().asItem(),
            Items.FLINT_AND_STEEL,
            DoTBItemsRegistry.INSTANCE.PRECOLUMBIAN_EMBLEM.get()

    ),
    FRENCH("french", null,
            Blocks.OAK_PLANKS.asItem(),
            Blocks.OAK_STAIRS.asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_PLANKS_PLATE.get().asItem(),
            Blocks.OAK_SLAB.asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_PLANKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_SUPPORT_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_SUPPORT_BEAM.get().asItem(),
            Blocks.STRIPPED_OAK_LOG.asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_BEAM.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_PERGOLA.get().asItem(),
            Blocks.OAK_FENCE.asItem(),
            Blocks.OAK_FENCE_GATE.asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_LATTICE.get().asItem(),
            Blocks.OAK_DOOR.asItem(),
            Blocks.OAK_TRAPDOOR.asItem(),
            Blocks.OAK_LEAVES.asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_LEAVES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.OAK_LEAVES_EDGE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.COBBLED_LIMESTONE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.COBBLED_LIMESTONE_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.COBBLED_LIMESTONE_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.COBBLED_LIMESTONE_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.COBBLED_LIMESTONE_EDGE.get().asItem(),
            // DoTBBlocksRegistry.INSTANCE.COBBLED_LIMESTONE_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BRICKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BRICKS_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BRICKS_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BRICKS_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BRICKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_SIDED_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BRICKS_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_BALUSTER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_GARGOYLE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_FIREPLACE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.REINFORCED_GOLDEN_WROUGHT_IRON_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.REINFORCED_BLACK_WROUGHT_IRON_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLACK_WROUGHT_IRON_BALUSTER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.BLACK_WROUGHT_IRON_FENCE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROOFING_SLATES.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROOFING_SLATES_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROOFING_SLATES_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROOFING_SLATES_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROOFING_SLATES_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.ROOFING_SLATES_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.LIMESTONE_CHIMNEY.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.IRON_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.IRON_FANCY_LANTERN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.CANDLESTICK.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.FIREPLACE.get().asItem(),
            Items.FLINT_AND_STEEL,
            DoTBItemsRegistry.INSTANCE.FRENCH_EMBLEM.get()
    ),
    PERSIAN("persian", null,

            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_TURQUOISE_PATTERN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_TURQUOISE_PATTERN_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_TURQUOISE_PATTERN_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_TURQUOISE_PATTERN_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_TURQUOISE_PATTERN_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_BRICKS_TURQUOISE_PATTERN_WALL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_SCULPTED_RELIEF.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SANDSTONE_CRENELATION.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_TRADITIONAL.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_DELICATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_BORDER.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_PATTERN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_GEOMETRIC.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_RECESS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_RELIEF.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.MORAQ_MOSAIC_COLUMN.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PERSIAN_CARPET_RED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PERSIAN_CARPET_DELICATE_RED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GOLD_PLATED_SMOOTH_BLOCK.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GOLD_PLATED_SMOOTH_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GOLD_PLATED_SMOOTH_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GOLD_PLATED_SMOOTH_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GOLD_PLATED_SMOOTH_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GOLD_PLATED_SMOOTH_WALL.get().asItem(),
            DoTBItemsRegistry.INSTANCE.UNFIRED_CLAY_TILE.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE_WHITE.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE_CYAN.get(),
            DoTBItemsRegistry.INSTANCE.CLAY_TILE_BLUE.get(),
            DoTBItemsRegistry.INSTANCE.PERSIAN_EMBLEM.get()
    ),
    CHINESE("chinese", null,
            DoTBBlocksRegistry.INSTANCE.SLATE_BRICKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SLATE_BRICKS_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SLATE_BRICKS_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SLATE_BRICKS_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SLATE_BRICKS_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.SLATE_BRICKS_WALL.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_LOG_STRIPPED.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_PLANKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_PLATE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_SLAB.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_EDGE.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_DOOR.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_SHUTTERS.get().asItem(),


            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_FANCY_RAILING.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.WAXED_ACACIA_ROOF_SUPPORT.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.PAINTED_ACACIA_PLANKS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.PAINTED_ACACIA_FENCE.get().asItem(),

            DoTBBlocksRegistry.INSTANCE.GREEN_PAINTED_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PAINTED_STRAIGHT_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PAINTED_DIAMOND_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_PAINTED_DECORATED_WINDOW.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_ROOF_TILES.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_SMOOTH_TILES.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.GREEN_SMOOTH_TILES_STAIRS.get().asItem(),
            DoTBBlocksRegistry.INSTANCE.RED_ROUND_PAPER_LANTERN.get().asItem()

            );


    private final String name;
    private final String youtubePlaylist;
    private final Component translation;
    private final ArrayList<Item> items = new ArrayList<>();
    private final List<SubTab> subTabs;

    CreativeInventoryCategories(String name, @Nullable String youtubePlaylist, Item... items) {
        this.name = name;
        this.youtubePlaylist = youtubePlaylist;
        this.translation = Component.translatable("gui." + MOD_ID + "." + name);
        this.items.addAll(Arrays.asList(items));
        this.subTabs = List.of();
    }

    CreativeInventoryCategories(String name, @Nullable String youtubePlaylist, List<SubTab> subTabs) {
        this.name = name;
        this.youtubePlaylist = youtubePlaylist;
        this.translation = Component.translatable("gui." + MOD_ID + "." + name);
        this.subTabs = subTabs;
    }

    public String getName() {
        return this.name;
    }

    @Nullable
    public String getYoutubePlaylist() {
        return this.youtubePlaylist;
    }

    public Component getTranslation() {
        return this.translation;
    }

    public List<Item> getItems() {
        return this.items;
    }

    public List<SubTab> getSubTabs() {
        return this.subTabs;
    }

    public boolean hasSubTabs() {
        return !this.subTabs.isEmpty();
    }

    public List<Item> getSubTabItems(int subTabIndex) {
        if (!hasSubTabs()) return this.items;
        int idx = Math.max(0, Math.min(subTabIndex, subTabs.size() - 1));
        return subTabs.get(idx).items();
    }

    public record SubTab(String nameKey, List<Item> items) {
        public SubTab(String nameKey, Item... items) {
            this(nameKey, Arrays.asList(items));
        }

        public Component getTooltip() {
            return Component.translatable("tooltip." + MOD_ID + ".subtab." + nameKey);
        }
    }
}