plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

neoForge  {
    version = neoforge_version

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath) //["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    compileOnly project(":common")

    // Mod compatibility

    runtimeOnly("maven.modrinth:rei:b8gfS9Je")
    runtimeOnly("maven.modrinth:cloth-config:izKINKFg")
    runtimeOnly("maven.modrinth:architectury-api:ZxYGwlk0")
    //runtimeOnly("maven.modrinth:geckolib:RVIo5f6E")

    //modRuntimeOnly("maven.modrinth:lets-do-vinery:YpD6ue8A")
    //modRuntimeOnly("maven.modrinth:farmers-delight:NcRp00OO")
    //runtimeOnly("maven.modrinth:critters-and-companions:C0bnFRAK")
    runtimeOnly("maven.modrinth:fusion-connected-textures:1.2.11-neoforge-mc1.21")

    //annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    implementation 'org.jetbrains:annotations:26.0.2'
}

publishMods {
    file = jar.archiveFile
    modLoaders.add("neoforge")
}
